# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ceres_helloworld <- function() {
    .Call(`_ceres_ceres_helloworld`)
}

rcpp_hello_world <- function() {
    .Call(`_ceres_rcpp_hello_world`)
}

